### ISSUE TITLE
Account refresh problem

### ISSUE THREAD

**Issue by wanpixiaozi** [dacelee/MOACMask#3]
I used moacmask on google browser, and choose moac testnet, i transfer 10 MC to my account1 on moacmask, the testnet browser show the transfer is ok, but i can't got new balance, the balance on moacmask is still 0mc, i wait 1 minute, balance not changed on moacmask.
After 1 minutes, i relogin my account, balance changed to the same as browser.

**Comment by dacelee** [comment]
Please wait for TX confirmation.

**Comment by dacelee** [comment]
Moacmask RPC JSON is provided by the Silicon Valley team. There may be delays.
